### ISSUE TITLE
Calls to setUserEmail and setUserFullName not working

### ISSUE THREAD

**Issue by ghost** [freshdesk/mobihelp-phonegap#12]
I've tried calling setUserEmail() and setUserFullName() before AND after initializing the object, but it doesn't appear to work.  I would think that at minimum, the user's email address would prepopulate when showSupport() or showFeedback() is called.

**Comment by rsquare2014** [comment]
This seems to be working as expected. call setUserEmail() and setUserFullName() after initializing Mobihelp. This can only be used to set email and name before the user creates a ticket and not to update them after a ticket is created
