### ISSUE TITLE
Android build issue with latest cordova lib

### ISSUE THREAD

**Issue by abouttimeruss** [freshdesk/mobihelp-phonegap#15]
With an upgrade in an ionic framework application with the latest cordova lib 6.4.0, I get an error building android. Builds have been fine prior to this cordova update. I confirmed that building a brand new fresh ionic app with nothing in it but the FreshDesk phonegap plugin gets the same error: 

Error: /Users/russ/source/fdtest/platforms/android/gradlew: Command failed with exit code 1 Error output:
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'android'.
> Cannot evaluate module MobihelpSDK : Configuration with name 'debug' not found.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by ilyakvan** [comment]
Same problem

**Comment by madc0w** [comment]
Same here.  Can't use Freshdesk any more.

**Comment by abouttimeruss** [comment]
I got a response from FreshDesk support:

_Unfortunately currently we have discontinued supporting bugs on Freshdesk SDK as we have moved with the product Hotline. So we suggest you to switch to Hotline as we would not be able to support you with this bug._

For more information on Hotline, please visit - https://hotline.io/

**Comment by tryprasannan** [comment]
This product has been discontinued and we no longer support this. Please write to us at support@hotline.io to discuss the way forward
