### ISSUE TITLE
Cordova 7.0+ Incompatibility

### ISSUE THREAD

**Issue by SpikePuppet** [freshdesk/mobihelp-phonegap#16]
Hello

Currently I'm using this plugin with Cordova 7.0.1, but as mentioned in the article below, without a package.json file its not possible to add this plugin to our app.

I was wondering if it was possible for a package.json file to be included with the repo. If needed i can upload the one i've generated. 

Article:
http://ourcodeworld.com/articles/read/455/cordova-error-failed-to-fetch-plugin-npm-not-being-able-to-find-a-package-json-in-a-package-you-are-trying-to-install

**Comment by tryprasannan** [comment]
@SpikePuppet This product has been discontinued and we no longer support this. Please write to us at support@hotline.io to discuss the way forward
