### ISSUE TITLE
Could not find com.android.support:appcompat-v7:21.0.0.

### ISSUE THREAD

**Issue by rajeshvishnani** [freshdesk/mobihelp-phonegap#2]
Hi, here is another issue, the plugin was installed successfully, but when i built the android version i got below error, i saw this somewhere in the documentation that the appcompat is required, but i dont know the steps about how to install the jar, please suggest something.

FAILURE: Build failed with an exception.
- What went wrong:
  A problem occurred configuring root project 'android'.
  
  > A problem occurred configuring project ':cordova-plugin-freshdesk-mobihelp:ged
  > tests-MobihelpSDK'.
  > Could not resolve all dependencies for configuration ':cordova-plugin-fresh
  > desk-mobihelp:gedtests-MobihelpSDK:_debugCompile'.
  > Could not find com.android.support:appcompat-v7:21.0.0.
  >     Searched in the following locations:
  >         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/21.0
  > .0/appcompat-v7-21.0.0.pom
  >         https://repo1.maven.org/maven2/com/android/support/appcompat-v7/21.0
  > .0/appcompat-v7-21.0.0.jar
  >     Required by:
  >         android.cordova-plugin-freshdesk-mobihelp:gedtests-MobihelpSDK:unspe
  > cified
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

BUILD FAILED

**Comment by SatheeshJM** [comment]
Please make sure you have the 'Android support repository' installed with your Android SDK, which has the appcompat library. 
https://developer.android.com/tools/support-library/setup.html

**Comment by rajeshvishnani** [comment]
@SatheeshJM 
Oh yeah, i fixed it and here is one more and last i think, because this generated at debug level.

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':dexDebug'.
  > com.android.ide.common.internal.LoggedErrorException: Failed to run command:

Error Code:
        2
Output:

```
    UNEXPECTED TOP-LEVEL EXCEPTION:
    com.android.dex.DexException: Multiple dex files define Landroid/support
```

/v7/app/ActionBar$Callback;
                at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.ja
va:596)
                at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:
554)
                at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:
535)
                at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)

```
            at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
            at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main
```

.java:454)
                at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
                at com.android.dx.command.dexer.Main.run(Main.java:246)
                at com.android.dx.command.dexer.Main.main(Main.java:215)
                at com.android.dx.command.Main.main(Main.java:106)
- Try:
  Run with --stacktrace option to get the stack trace. Run with --info or --debug
  option to get more log output.

BUILD FAILED

**Comment by SatheeshJM** [comment]
Looks like appcompat is being included as a dependancy twice to your project... 
This can be checked as follows : 
1. Navigate to the android project folder inside your project 
  PROJECT_FOLDER/platforms/android
2. Run the command:  
  gradle -q dependencies

This will show a dependancy graph for your project.  If appcompat is listed twice there, you will have to exclude appcompat from one of the plugins..

**Comment by rajeshvishnani** [comment]
@SatheeshJM OK i see the appcompat was attached twice, now the android build is successfully generated, but when iuse <a onclick="window.Mobihelp.showSupport()"> Support </a>, i dont see any change in the app, as the questions are already added via admin panel, also the initialization is done. please suggest.

**Comment by SatheeshJM** [comment]
Are you calling the showSupport function correctly? 
Adding the following would work : 
  in www/index.html (in body)
    `<button id="LaunchSupport"> LaunchSupport </button>`
  in www/index.js (after calling window.Mobihelp.init)
    `document.getElementById("LaunchSupport").onclick = function(){
            window.Mobihelp.showSupport();
        };`

**Comment by rajeshvishnani** [comment]
<script type="text/javascript">
                $(document).ready(function (e) {                    
                    window.Mobihelp.init({
                        appKey: "gedtest-1-52f6a9734b424bccaea9c50f4f203333",
                        appSecret: "6d7ca8391694362a6f2a961f31e4b7946b2ceab0",
                        domain: "https://gedeasy.freshdesk.com"
                    });
					document.getElementById("LaunchSupport").onclick = function(){ window.Mobihelp.showSupport(); };
                });                
            </script>
This is my JS and

<button id="LaunchSupport"> LaunchSupport </button>

is my HTML, am i doing anything wrong?

**Comment by rajeshvishnani** [comment]
<script type="text/javascript">
                $(document).ready(function (e) {                    
                    window.Mobihelp.init({
                        appKey: "gedtest-1-52f6a9734b424bccaea9c50f4f203333",
                        appSecret: "6d7ca8391694362a6f2a961f31e4b7946b2ceab0",
                        domain: "https://gedeasy.freshdesk.com"
                    });
					document.getElementById("LaunchSupport").onclick = function(){ window.Mobihelp.showSupport(); };
                });                
            </script>

**Comment by rajeshvishnani** [comment]
```
<script type="text/javascript">
                $(document).ready(function (e) {                    
                    window.Mobihelp.init({
                        appKey: "gedtest-1-52f6a9734b424bccaea9c50f4f203333",
                        appSecret: "6d7ca8391694362a6f2a961f31e4b7946b2ceab0",
                        domain: "https://gedeasy.freshdesk.com"
                    });
					document.getElementById("LaunchSupport").onclick = function(){ window.Mobihelp.showSupport(); };
                });                
            </script>
```

**Comment by SatheeshJM** [comment]
@rajeshvishnani  
Hey can you please raise a ticket in our support portal? 
Sending a mail to support@freshdesk.com would do. 
We would help you resolve the issue

**Comment by rajeshvishnani** [comment]
i did but i thought it was time consuming, and it looks like we are almost done with it and there is minor error in the code i pasted above, if you can help, it would be great.
