### ISSUE TITLE
iOS 9 Issue: Unexpected CFBundleExecutable Key

### ISSUE THREAD

**Issue by MatthewHallCom** [freshdesk/mobihelp-phonegap#4]
Screenshot attached! Plugin was removed and added again to ensure newest version.

![screen shot 2015-09-12 at 9 12 43 pm](https://cloud.githubusercontent.com/assets/1230091/9835206/267673da-5993-11e5-8526-ea7aa81ca5ed.jpg)

**Comment by hrishikesh-p** [comment]
@nowned  Updated the iOS SDK to v1.6.2  which contains fixes and support for iOS9 .  Please note that this version also introduces changes to the theming on iOS
