### ISSUE TITLE
Mobihelp.getUnreadCountAsync only returning correct value after launching Mobihelp popup

### ISSUE THREAD

**Issue by javacado** [freshdesk/mobihelp-phonegap#8]
IOS
I am running Mobihelp.getUnreadCountAsync() every 30 seconds, which is returning the correct value ONLY after I launch the popup with Mobihelp.showSupport()

Before I launch the popup Mobihelp.getUnreadCountAsync() returns 0
Once I launch the popup and wait a little bit, then Mobihelp.getUnreadCountAsync() returns the current value.

I want to let my users know if they have a support request answer, without them having to navigate into the support page of my app. 

Am I doing something wrong?

Also, I can't seem to affect the theme. I change the value but nothing changes. How can I troubleshoot that? 

Thanks!!!!

**Comment by hrishikesh-p** [comment]
The getUnreadCountAsync only goes to the server every 2 mins . It is designed such because there were instances where some implementations were calling that function every second which resulting in rate limiting those calls. 

Although this limit may seem high when testing, If you take into account the agent response time the delay will not be noticed by the end user. 

As for the theme .. Can you please check if the theme file name matches and is included in your Copy Resources section of your Build Phases?

**Comment by javacado** [comment]
Thanks for the response! I understand about the 2 minutes - I figured it out that it was eventually checking - but ONLY if I first launched the popup. If I don't ever launch the popup, getUnreadCountAsync returns zero. My assumption is that the getUnreadCountAsync just looks into the mobihelp object to get the current value it's storing - rather than reaching out to a server to get it. Is that right?

Since it's chat based, that makes sense. I was hoping to use it more like a email substitute where if I responded the next day or 2 the user would see they had a message waiting the next time they launched the app. The message is waiting for them like it should be, but my code can't detect it until they launch the popup to initialize mobihelp.

As to the theme - I found MDResource.bundle, which is included in the Copy Bundle Resources. However, in that bundle, in the themes folder there is only FDLightTheme.plist. I was trying to use the FDDarkTheme - but it's not in the repo.

**Comment by hrishikesh-p** [comment]
Could you please check again. getUnreadCountAsync will get you the latest number from the server with a time delay. getUnreadCount works as you had described it ( looking at a local value ) 

We don't include the DarkTheme anymore . can you please use the FDLightTheme ? You can also include a theme file in your project with your customizations and provide that name to the theme file name in the config .

**Comment by javacado** [comment]
You're right - it worked! It took about 10 minutes.... but that might be b/c I was hitting getUnreadCountAsync every second (I meant for it to be every minute) - but I changed that to check every 2 minutes so it should be fine now. 

Thanks for the great plugin, I really appreciate your hard work!!

**Comment by javacado** [comment]
BTW - One minor but significant update you might make is to disable the 'Submit' link on the Submit Ticket screen after it's clicked (When you create a ticket). Since there is a delay in the sending process, I instinctively clicked it again thinking maybe it didn't register the first time. It's likely somethign that will happen to users and since it creates a duplicate ticket it could be problematic. Just a suggestion.
