### ISSUE TITLE
EXC_BAD_ACCESS when run application

### ISSUE THREAD

**Issue by kimalec** [freshdesk/mobihelp-phonegap#9]
I'm developing with ionic framework.

When pluginName is 'mobihelpplugin' a crash caused by EXC_BAD_ACCESS
<img width="790" alt="2016-02-03 22 19 41" src="https://cloud.githubusercontent.com/assets/6895272/12785543/5a6d7978-cad0-11e5-8061-8ce9670c0676.png">

<img width="655" alt="2016-02-03 22 20 19" src="https://cloud.githubusercontent.com/assets/6895272/12785560/6d076472-cad0-11e5-96e2-dbfc49128333.png">

xcode version is 7.2

**Comment by rsquare2014** [comment]
Can you please uninstall and then update the plugin to the latest version and check if the issue still persists?
